name       : mkvtoolnix
version    : 72.0.0
release    : 78
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-72.0.0.tar.xz : 3bd1005baf397f1d70619c2f2c52af9de8ce75995830e790e429c0943fd08000
homepage   : https://gitlab.com/mbunkus/mkvtoolnix
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(dvdread)
    - pkgconfig(flac)
    - pkgconfig(fmt)
    - pkgconfig(libcmark)
    - pkgconfig(libcurl)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(vorbis)
    - docbook-xml
    - gtest-devel
    - libboost-devel
    - ruby
setup      : |
    %autogen --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
check      : |
    rake tests:run_unit
