name       : mkvtoolnix
version    : 26.0.0
release    : 31
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-26.0.0.tar.xz : d51e63c356f9f0c92cc0b01ff6e78253954c74186be6ef4c40c5690d18fda7e0
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libcurl)
    - pkgconfig(libcmark)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(vorbis)
    - docbook-xml
    - gtest-devel
    - libboost-devel
    - ruby
setup      : |
    %configure --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
check      : |
    rake tests:run_unit
