name       : mkvtoolnix
version    : 56.1.0
release    : 66
source     :
    - https://gitlab.com/mbunkus/mkvtoolnix/-/archive/release-56.1.0/mkvtoolnix-release-56.1.0.tar.bz2 : e56068b69d13ad4a15a0afd99a204a0557980195f3c0c2d64d33cc18369a8ab1
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(dvdread)
    - pkgconfig(flac)
    - pkgconfig(fmt)
    - pkgconfig(libcmark)
    - pkgconfig(libcurl)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(vorbis)
    - docbook-xml
    - gtest-devel
    - libboost-devel
    - ruby
setup      : |
    %autogen --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
check      : |
    rake tests:run_unit
