name       : mkvtoolnix
version    : 8.8.0
release    : 1
source     :
    - https://github.com/mbunkus/mkvtoolnix/archive/release-8.8.0.tar.gz : 6eb70126ecee3d5f2049ada51fcfde71f36d8477b87d717137857d251362a281
license    : GPL-2.0
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(Qt5Core)
    - pkgconfig(libebml)
    - pkgconfig(flac)
    - pkgconfig(libmatroska)
    - libboost-devel
    - ruby
setup      : |
    ./autogen.sh --prefix=/usr
    %configure
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
