name       : mkvtoolnix
version    : 9.4.2
release    : 6
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-9.4.2.tar.xz : df2c3773c0e7a75d88e75906cc425f9ed7f07ce36a99854162e14202ccd42904
license    : GPL-2.0
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Core)
    - pkgconfig(vorbis)
    - libboost-devel
    - ruby
setup      : |
    %configure --disable-static
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
