name       : mkvtoolnix
version    : 15.0.0
release    : 19
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-15.0.0.tar.xz : 73dc3b6f0a7147e28c06f44427fa0e824d0a4129e40c942d7642d9f451a51195
license    : GPL-2.0
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libcurl)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(vorbis)
    - docbook-xml
    - libboost-devel
    - ruby
setup      : |
    %configure --disable-static --disable-update-check
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
