name       : mkvtoolnix
version    : 9.1.0
release    : 3
source     :
    - https://github.com/mbunkus/mkvtoolnix/archive/release-9.1.0.tar.gz : 0a9f8fc3af88edf833f97e6f1df6d72c2aada8bd5856654fff6527b8baed9891
license    : GPL-2.0
summary    : MKV Toolkit for Linux
component  : desktop.multimedia
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(Qt5Core)
    - pkgconfig(libebml)
    - pkgconfig(flac)
    - pkgconfig(libmatroska)
    - libboost-devel
    - ruby
setup      : |
    ./autogen.sh --prefix=/usr
    %configure
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
