name       : mkvtoolnix
version    : 9.6.0
release    : 9
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-9.6.0.tar.xz : ebab8dcc59533d248b127d375286eb47880a222ef68ff7a10e1c87d49dbd86bb
license    : GPL-2.0
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Core)
    - pkgconfig(vorbis)
    - libboost-devel
    - ruby
setup      : |
    %configure --disable-static
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
