name       : mkvtoolnix
version    : 49.0.0
release    : 59
source     :
    - https://gitlab.com/mbunkus/mkvtoolnix/-/archive/release-49.0.0/mkvtoolnix-release-49.0.0.tar.bz2 : cb259150e306e4b2a36d6bbc4950cfc460b33ca2659cd8a8e793cb5d1be747dc
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(flac)
    - pkgconfig(fmt)
    - pkgconfig(libcurl)
    - pkgconfig(libcmark)
    - pkgconfig(dvdread)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(vorbis)
    - docbook-xml
    - gtest-devel
    - libboost-devel
    - ruby
setup      : |
    %autogen --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
check      : |
    rake tests:run_unit
