name       : mkvtoolnix
version    : 41.0.0
release    : 49
source     :
    - https://gitlab.com/mbunkus/mkvtoolnix/-/archive/release-41.0.0/mkvtoolnix-release-41.0.0.tar.bz2 : 21114dc1e312889bcfb2fa16dafe4772ce86d01076553b896ab4151a7c69ef75
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(flac)
    - pkgconfig(libcurl)
    - pkgconfig(libcmark)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(vorbis)
    - docbook-xml
    - fmt-devel
    - gtest-devel
    - libboost-devel
    - ruby
setup      : |
    %autogen --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
check      : |
    rake tests:run_unit
