name       : mkvtoolnix
version    : 16.0.0
release    : 20
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-16.0.0.tar.xz : 5dfb2517003f69f3d8b942751200122c2e4cad2a8675b6fc2dfaad5c98e946e0
license    : GPL-2.0
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libcurl)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(vorbis)
    - docbook-xml
    - libboost-devel
    - ruby
setup      : |
    %configure --disable-static --disable-update-check
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
