name       : mkvtoolnix
version    : 14.0.0
release    : 18
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-14.0.0.tar.xz : 86aa96acb26f7ef9d7afb4d0c1fa1a086b398d563b77372c436044c3c6bba78c
license    : GPL-2.0
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libcurl)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(vorbis)
    - docbook-xml
    - libboost-devel
    - ruby
setup      : |
    %configure --disable-static
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
