name       : mkvtoolnix
version    : 9.7.0
release    : 10
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-9.7.0.tar.xz : 8a10d93f512ff84a42bf8244759bc65257a527604a4be0a696e9853a7403043a
license    : GPL-2.0
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libcurl)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Core)
    - pkgconfig(vorbis)
    - libboost-devel
    - ruby
setup      : |
    %configure --disable-static
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
