name       : mkvtoolnix
version    : 21.0.0
release    : 24
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-21.0.0.tar.xz : ad6d1d0ba40b153c155d5b26425e88531b24bb9969bac0341040e48cbb77c391
license    : GPL-2.0
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libcurl)
    - pkgconfig(libcmark)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(vorbis)
    - docbook-xml
    - gtest-devel
    - libboost-devel
    - ruby
setup      : |
    %configure --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
check      : |
    rake tests:run_unit

