name       : mkvtoolnix
version    : 9.0.1
release    : 2
source     :
    - https://github.com/mbunkus/mkvtoolnix/archive/release-9.0.1.tar.gz : ab7a348b2e0ae70899303e474e4295c2f0f12b713e7b9705b55f7309d2018f32
license    : GPL-2.0
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(Qt5Core)
    - pkgconfig(libebml)
    - pkgconfig(flac)
    - pkgconfig(libmatroska)
    - libboost-devel
    - ruby
setup      : |
    ./autogen.sh --prefix=/usr
    %configure
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
