name       : mkvtoolnix
version    : 61.0.0
release    : 72
source     :
    - https://gitlab.com/mbunkus/mkvtoolnix/-/archive/release-61.0.0/mkvtoolnix-release-61.0.0.tar.bz2 : cd8017c3639b5bc71e4d21c9326d0f2dc75604ef8624b72d5d907140bbbb5c1e
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(dvdread)
    - pkgconfig(flac)
    - pkgconfig(fmt)
    - pkgconfig(libcmark)
    - pkgconfig(libcurl)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(vorbis)
    - docbook-xml
    - gtest-devel
    - libboost-devel
    - ruby
setup      : |
    %autogen --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
check      : |
    rake tests:run_unit
