name       : mkvtoolnix
version    : 9.2.0
release    : 4
source     :
    - https://github.com/mbunkus/mkvtoolnix/archive/release-9.2.0.tar.gz : d1a90d1842003bd0af7ade884cd8428fe7dce95ffd80440f7960c821d727ac6d
license    : GPL-2.0
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Core)
    - pkgconfig(vorbis)
    - libboost-devel
    - ruby
setup      : |
    %autogen
build      : |
    rake -j %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
