name       : mkvtoolnix
version    : 28.1.0
release    : 33
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-28.1.0.tar.xz : 26b949871afcfcc0bf6b4ccfa170de73d34d25c83f2ead69327025194f54d615
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(flac)
    - pkgconfig(libcurl)
    - pkgconfig(libcmark)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(vorbis)
    - docbook-xml
    - gtest-devel
    - libboost-devel
    - ruby
setup      : |
    %configure --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
check      : |
    rake tests:run_unit
